#!/bin/sh

set -eu
case "$AUTOSERVER_WHICH_CONTAINER" in
	1)
		FSROOT_RW="/rw_disk/containers/inner_b_fsroot_rw"
		ETC_DIR="/__autoserver-local__/server1/inner_b_etc"
		ROUTES="100.78.20.64/26 2602:806:a000:2a88::/64"
		LOCAL_ADDR="0.0.0.11"
		NETNS_AMBIENT="/run/netns/server1-wg_pjtl"
		;;
	2)
		FSROOT_RW="/rw_disk/containers/inner_c_fsroot_rw"
		ETC_DIR="/__autoserver-local__/server1/inner_b_etc"
		ROUTES="172.26.0.64/26 fd48:774f:d9a1:8103::/64"
		LOCAL_ADDR="0.0.0.11"
		NETNS_AMBIENT="/run/netns/server1-u-relay-main"
		;;
esac
		
cd /proc/self/fd/"$2"/ns
nsenter --user=user --ipc=ipc --mount=mnt unshare -n sh -eu -c '
/__autoserver__/ctrtool rootfs-mount -o mount_sysfs=1 -o root_link_opts=usr_ro /proc/driver
rm -f /proc/driver/etc
cp -r -- "$2" /proc/driver/etc
/__autoserver__/ctrtool mount_seq -c /proc/driver -m _fsroot_rw -E -s "$1" -Ob -m ctr_fs1 -E -s /containers/mounts/mix_1 -Ob -m ctr_fs2 -E -s /containers/mounts/mix_2 -Ob -m _fsroot_ro -E -s ctr_fs1/generic -Ob -D run/netns -M 0755 -m run/netns/__host__ -f -s /proc/self/ns/net -K -Ob -m socketbox_host -E -s /run/socketbox -Ob
' _ "$FSROOT_RW" "$ETC_DIR"

nsenter --net="$NETNS_AMBIENT" sh -eu -c 'ip link add to_srv type veth peer name eth0 netns /proc/self/fd/"$1"/root/proc/driver/run/netns/__host__; ip addr add "$2" dev to_srv; ip link set to_srv address "00:00:5e:00:53:20" up; for r in $3; do ip route add "$r" via inet6 "fe80::200:5eff:fe00:5321" dev to_srv; done' _ "$2" "$LOCAL_ADDR" "$ROUTES"
