#!/bin/sh
set -eu
ip link set lo up
ip link add br0 type bridge
sysctl -w net.ipv6.conf.br0.accept_ra=0
ip addr add '172.30.7.241/21' dev br0
ip link set br0 up
ip route add 0.0.0.0/0 via 172.30.0.1
# ip link set enp1s0 master br0 up
