<?php
# This file was automatically generated by the MediaWiki 1.35.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# This file is from MediaWiki, which is licensed under the GNU General
# Public License version 2.

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Peter Jin (.org)";
$wgMetaNamespace = "Peterjin.org";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## The protocol and server name to use in fully-qualified URLs
# $wgServer = "https://website.peterjin.org";
if ($_SERVER["HTTP_HOST"] == "wiki.secure.peterjin.org") {
        $wgServer = "https://wiki.secure.peterjin.org";
} else {
        $wgEnableCanonicalServerLink = true;
        $wgServer = "https://website.peterjin.org";
}
## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "/w/images/thumb/a/a6/Profile_image.png/135px-Profile_image.png";
# $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@invalid.invalid";
$wgPasswordSender = "apache@invalid.invalid";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "peterjin_org_wiki";
$wgDBuser = "mediawiki";
# authenticated via unix_socket/auth_socket
$wgDBpassword = "";

# MySQL specific settings
$wgDBprefix = "wiki_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgUploadDirectory = "/_fsroot_rw/mediawiki/data/images";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";
exit;
# XXX set this in production
$wgSecretKey = "";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "3";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
# XXX set this in production
$wgUpgradeKey = "";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "Creative Commons Attribution-ShareAlike 4.0";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";


## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
wfLoadSkin("MonoBook");
wfLoadSkin("Timeless");
wfLoadSkin("Vector");
wfLoadSkin("MinervaNeue");
$wgDefaultSkin = "timeless";
# $wgDefaultSkin = "vector";
# $wgDefaultMobileSkin = "minerva";

# End of automatically generated settings.
# Add more configuration options below.
$wgExtraNamespaces[3000] = "Aliases_3000";
$wgExtraNamespaces[3001] = "Aliases_3000_talk";
$wgExtraNamespaces[3002] = "Snippets";
$wgExtraNamespaces[3003] = "Snippets_talk";
$wgExtraNamespaces[3004] = "Blog";
$wgExtraNamespaces[3005] = "Blog_talk";
wfLoadExtension("CategoryTree");
wfLoadExtension("CheckUser");
wfLoadExtension("Cite");
wfLoadExtension("WikiEditor");
wfLoadExtension("MultimediaViewer");
wfLoadExtension("Scribunto");
wfLoadExtension("AddHTMLMetaAndTitle");
wfLoadExtension("ParserFunctions");
wfLoadExtension("SyntaxHighlight_GeSHi");
wfLoadExtension("TextExtracts");
wfLoadExtension("PageImages");
wfLoadExtension("Popups");
wfLoadExtension("HitCounters");
wfLoadExtension("MobileFrontend");
wfLoadExtension("VisualEditor");
wfLoadExtension("RelatedArticles");
$wgRelatedArticlesFooterWhitelistedSkins = ["minerva", "timeless"];
$wgAllowDisplayTitle = true;
$wgRestrictDisplayTitle = false;
$wgScribuntoDefaultEngine = "luastandalone";
$wgEnableCountersAtTheFooter = true;
$wgFileExtensions[] = "svg";
$wgFileExtensions[] = "pdf";
$wgFileExtensions[] = "ogg";
$wgFileExtensions[] = "txt";
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgContentNamespaces = [NS_MAIN, 3000, 3002, 3004];
$wgNoFollowDomainExceptions = ["peterjin.org", "ipv6.bible", "ipv6-things.com", "pjin.org"];
$wgCookiePrefix = "__Host-wiki";
$wgExemptFromUserRobotsControl = [NS_MAIN, 3000, 3002, 3004, -1];
$wgNamespaceRobotPolicies[-1] = "";


