#!/bin/sh

set -eu
nsenter --net=/run/netns/__host__ sh -eu -c '
ip link set lo up
ip route add unreachable "fd48:774f:d9a1:8103::/64" table main
ip route add unreachable "172.26.0.64/26" table main
ip addr add "172.26.0.64" dev eth0
ip addr add "fd48:774f:d9a1:8103::1" dev eth0
ip link set eth0 address 00:00:5e:00:53:21 up
ip route add ::/0 via inet6 fe80::200:5eff:fe00:5320 dev eth0
ip route add 0.0.0.0/0 via inet6 fe80::200:5eff:fe00:5320 dev eth0
'
ln -s /_fsroot_ro/etc/_mysql /etc/mysql
mysql_install_db -u mysql --force || :
exec /ctr_fs1/_system/bin/ctrtool mini-init2 \
	-n /usr/bin/mysqld_safe -c--skip-networking -r 10 \
	-n /bin/sh -c /etc/matrix/start_nginx_2.sh -c-c/etc/nginx/nginx_2.conf -r 10 \
	-n /etc/matrix/start_pdns.sh -r10 \
	-n /etc/start-u-relay.sh -r9 \
	-n /usr/bin/nsenter -c--net=/run/netns/__host__ /usr/sbin/ntpd -c-u ntp:ntp -c-c /etc/ntp.conf -c -n -r10 \
	-n /ctr_fs1/_system/bin/socketbox -c-P '0:/socketbox_host/socketbox-u-relay.sock' -c-f /etc/socketbox-u-relay.conf -c-usocketbox -c-gsocketbox -c-x /run/socketbox -r10 \
	-s15 -a2
