#!/bin/sh

set -eu
cd /
ln -sT /_fsroot_ro/etc/services /etc/services
ln -sT /_fsroot_ro/etc/protocols /etc/protocols
mkdir -p /_fsroot_rw/var /run/sshd /run/systemd/system /run/syslog /run/pdns /var/log /var/lib /var/spool/rsyslog /var/spool/powerdns /run/socketbox
mkdir -pm 700 /_fsroot_rw/matrix /_fsroot_rw/mediawiki
ln -sfT /run /var/run
/ctr_fs1/_system/bin/ctrtool mount_seq -m /run/socketbox -s /run/socketbox -Ob -F8 -r
chown root:syslog /var/log
mkdir -pm 700 /var/lib/mysql; chown 'mysql:mysql' /var/lib/mysql
chmod 755 /etc
chmod 775 /var/log
chmod 700 /var/spool/powerdns
chown pdns:pdns /var/spool/powerdns
rsyslogd
chown root:socketbox /run/socketbox
chmod 2755 /run/socketbox
cd /run/socketbox
mkdir -m 2750 00001 00002 00003
setfacl -m 'u:matrix-synapse:rwx' 00002
chown matrix-synapse:matrix-synapse /_fsroot_rw/matrix
chown root:mediawiki /_fsroot_rw/mediawiki
chmod 755 /_fsroot_rw/mediawiki
# chmod 750 /_fsroot_rw/mediawiki
cd /
mount --bind /etc/resolv.conf-pjtl /ctr_fs2/matrix-synapse/etc/resolv.conf
exec /ctr_fs1/_system/bin/ctrtool launcher -L/var/log/container.log -m -p --mount-proc \
	/etc/__init2__
